### ISSUE TITLE
カテゴリごとに表示・非表示切替

### ISSUE THREAD

**Issue by ogsoonyn** [ogsoonyn/SelfMemoPrototype#2]
Category項目の内容限定でフィルターできるように
あるいはCategoryだけ別ComboBox等で選択できるように？

**Comment by ogsoonyn** [comment]
commit e258be1 にてカテゴリを選択するComboBox追加

**Comment by ogsoonyn** [comment]
実装しました。
v0.2 としてリリースしました。

**Comment by aoki2a** [comment]
(ここに書いた方がいいのかな？新しい、issueで上げた方がよいのかな？）
カテゴリによっては、選択用のショートカットが設定できるようになっていると、操作性Up

**Comment by ogsoonyn** [comment]
動作のイメージが掴めていませんが、カテゴリ名も自由に入力できる関係上、
「特定のカテゴリ」を決めるのが難しいような気がします。
とりあえず思いつく挙動をあげてみます。（どれがイメージ近いでしょうか。2かな）

1. 特定のショートカットキー入力で、直前に選択していたカテゴリでのフィルタON/OFF切り替え
2. 設定フォームとかで、ショートカットキーで適用したい「特定のカテゴリ」を選択する
3. ショートカットでカテゴリ選択のComboBoxにフォーカスが行くようにする。フォーカス後に上下キーでカテゴリ選択

なお、本issueは実装完ということでCloseしたいので、上記の件は別issueであげてもらえるとありがたいです。
