### ISSUE TITLE
Search/登録時の操作性向上について

### ISSUE THREAD

**Issue by aoki2a** [ogsoonyn/SelfMemoPrototype#4]
単語を検索しようとして、Searchフィールドに単語を入力した時、
まだ、登録されていない。ということに気が付き、登録しようとした時の動作

登録操作で、登録用のサブウィンドウが表示されるとき、Searchフィールドに文字列があれば、
その文字列が登録サブウィンドウの登録フィールドに反映されている状態で立ち上がって欲しい。

**Comment by ogsoonyn** [comment]
実装しました。

- 登録ウィンドウ起動時にSearch枠内の文字列をコピーする。
- メニュー項目で本機能のOFF/ONを切り替え可

**Comment by ogsoonyn** [comment]
v0.2 としてリリースしました。
