### ISSUE TITLE
[enh]登録された文字がURLフォーマットの時

### ISSUE THREAD

**Issue by aoki2a** [ogsoonyn/SelfMemoPrototype#9]
登録された文字がURLフォーマットの時、その文字列をクリックしたら、そのPathにジャンプ。
- ジャンプするかしないかは、選択可

ショートカット集としても使えるように。
- カテゴリに、「ショートカット」 もあるといいね。

よろ

**Comment by ogsoonyn** [comment]
version 0.3 リリースに実装しました。
（テーブル上でリンク化すると正常動作しないので制約付きですが…）
